sudo: false
language: c
addons:
  apt:
    packages:
      - libgmp-dev
cache:
  directories:
    - $HOME/.local/bin
    - $HOME/.stack
before_install:
  - sh bin/install-stack.sh
install:
  - stack setup
  - stack build --only-dependencies
#script:
#  - stack build
#  - stack sdist --pvp-bounds both
#  - stack exec biotech-weekly rebuild
#after_success:
#  - stack bin/deploy.hs
