name: biotech-weekly
version: '0.0.0'
description: A weekly email of the best news and articles on all things biotech. Stories are picked by hand from popular biotech sites.

category: Web
extra-source-files: content/**/*
github: bsima/biotech-weekly
license-file: LICENSE
license: MIT
maintainer: Ben Sima

dependencies: base
ghc-options: -Wall

library:
  dependencies:
    - hakyll
    - tagsoup
    - HTTP
    - flow
  source-dirs: lib

executables:
  biotech-weekly:
    dependencies: biotech-weekly
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
    main: biotech-weekly.hs
    source-dirs: exe
